### ISSUE TITLE
Can't SAVE to a format

### ISSUE THREAD

**Issue by cobbr2** [stevearc/dql#19]
I'm a total newbie to your project, and I'm probably reading the docs wrong, but I keep getting exceptions when I try to save to a non-default file format:

```
us-east-1> SCAN pid, sponsor, subsection FROM eligible.persons WHERE NOT attribute_exists(provenance_id) SCAN LIMIT 100 SAVE wackamole;
Saved 23 records to wackamole
us-east-1> SCAN pid, sponsor, subsection FROM eligible.persons WHERE NOT attribute_exists(provenance_id) SCAN LIMIT 100 SAVE wackamole.json;
Traceback (most recent call last):
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'DQLClient' object has no attribute 'do_SCAN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/cli.py", line 195, in start
    self.cmdloop()
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/cli.py", line 578, in default
    self._run_cmd(command)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/cli.py", line 602, in _run_cmd
    results = self.engine.execute(command)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/engine.py", line 972, in execute
    pretty_format)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/engine.py", line 299, in execute
    result = self._run(statement)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/engine.py", line 316, in _run
    return self._scan(tree)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/engine.py", line 608, in _scan
    return self._select(tree, True)
  File "/home/rcobb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dql/engine.py", line 593, in _select
    ofile.write(self._encoder.encode(item))
TypeError: a bytes-like object is required, not 'str'
us-east-1> 
```

This happens with both `.json` and `.csv`.  The values in the response columns are all UTF-8 (actually ASCII-7bit) strings or NULL.  I'm using:

```bash
$ dql --version
0.5.26
$ python --version
Python 3.6.5
```

**Comment by stevearc** [comment]
Alright, the first thing I would try is to add `ensure_ascii=False` to https://github.com/stevearc/dql/blob/fad509b3af7fde0b6f600ffbc100b2163430e8b2/dql/engine.py#L113-L114

If that doesn't fix it, try throwing this at the top:
```python
from builtins import str as text
```
And then add a case to the default JSON serializer:
https://github.com/stevearc/dql/blob/fad509b3af7fde0b6f600ffbc100b2163430e8b2/dql/engine.py#L32-L44
```python
if isinstance(value, text):
    return value.encode('utf-8')
```

Check if either of those helps for saving as JSON. If they do then we can figure out how to do something similar for csv.

**Comment by bpsommerville** [comment]
I also had this problem and was able to solve it by opening the file in non-binary mode.
i.e. in engine.py change:
```
            if ext.lower() in [".gz", ".gzip"]:
                ext = os.path.splitext(remainder)[1]
                opened = gzip.open(filename, "wb")
            else:
                opened = open(filename, "wb")
```
to
```
            if ext.lower() in [".gz", ".gzip"]:
                ext = os.path.splitext(remainder)[1]
                opened = gzip.open(filename, "wb")
            elif ext.lower() in [".csv", ".json"]:
                opened = open(filename, "w")
            else:
                opened = open(filename, "wb")
```
(the change is to pass "w" instead of "wb" in the open call
