### ISSUE TITLE
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by JimFinnerty** [stevearc/dql#8]
I'm attempting to download, install, and run dql on Mac OS, with Python 2.7.10:

$ python --version
Python 2.7.10
$ cd $home
$ curl -o install.py https://raw.githubusercontent.com/stevearc/dql/master/bin/install.py
$ python install.py 
$ ls -l | grep dql
-rwxr-xr-x    1 myusername  staff  4101688 Oct 25 15:24 dql

So far so good, but when I try to launch dql, this is what I get (see below).  Am I missing a pre-requisite, perhaps?   The error at the bottom is:

any.whl/dynamo3/result.py", line 64, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

 (Note that I have DynamoDB local running on this system also, if that matters)

$ ./dql -r us-east-1
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 326, in execute
  File ".bootstrap/_pex/pex.py", line 258, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 290, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 369, in _execute
  File ".bootstrap/_pex/pex.py", line 427, in execute_entry
  File ".bootstrap/_pex/pex.py", line 441, in execute_pkg_resources
  File ".bootstrap/pkg_resources/__init__.py", line 2235, in resolve
  File "/Users/jfinnerty/.pex/install/dql-0.5.22-py2-none-any.whl.12892f07e4140cc0af170e642e8c1659b535b944/dql-0.5.22-py2-none-any.whl/dql/**init**.py", line 8, in <module>
    from .cli import DQLClient
  File "/Users/jfinnerty/.pex/install/dql-0.5.22-py2-none-any.whl.12892f07e4140cc0af170e642e8c1659b535b944/dql-0.5.22-py2-none-any.whl/dql/cli.py", line 15, in <module>
    from .engine import FragmentEngine
  File "/Users/jfinnerty/.pex/install/dql-0.5.22-py2-none-any.whl.12892f07e4140cc0af170e642e8c1659b535b944/dql-0.5.22-py2-none-any.whl/dql/engine.py", line 15, in <module>
    from dynamo3 import (TYPES, DynamoDBConnection, DynamoKey, LocalIndex,
  File "/Users/jfinnerty/.pex/install/dynamo3-0.4.9-py2.py3-none-any.whl.b154b6913d278f7b90c1894c240209fbbc31c5c7/dynamo3-0.4.9-py2.py3-none-any.whl/dynamo3/**init**.py", line 2, in <module>
    from .batch import ItemUpdate
  File "/Users/jfinnerty/.pex/install/dynamo3-0.4.9-py2.py3-none-any.whl.b154b6913d278f7b90c1894c240209fbbc31c5c7/dynamo3-0.4.9-py2.py3-none-any.whl/dynamo3/batch.py", line 7, in <module>
    from .result import ConsumedCapacity
  File "/Users/jfinnerty/.pex/install/dynamo3-0.4.9-py2.py3-none-any.whl.b154b6913d278f7b90c1894c240209fbbc31c5c7/dynamo3-0.4.9-py2.py3-none-any.whl/dynamo3/result.py", line 64, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

As mentioned above, I have DynamoDB local running on my Mac, and I'd like to have dql connect with my local DynamoDB initially.  How do I configure dql to communicate with my DynamoDB local versus my AWS account in the specified region?

**Comment by stevearc** [comment]
This looks like the version of `six` that got installed it out of date. I don't know how that happened, but here are a couple suggestions.

1) You can inspect the current system version with `pip freeze | grep six`. I think you need version 1.10.0 or higher. You should be able to upgrade it with `pip install -U six==1.10.0` and then re-run the install script. The dql executable is built in a virtualenv, so I don't know how the system version would leak in, but this might fix it.

2) You could run the critical commands in the install script by hand and debug it as you go. It's not actually doing very much.
* `virtualenv venv`
* `source venv/bin/activate`
* `pip install pex six==1.10.0` (usually you would only install pex here, but this will make sure that you get the right version of six)
* `pex dql -m dql:main -o dql`
* `rm -rf venv`

Give one or both of those a try. Also to connect to DynamoDB Local initially just pass in `dql --host localhost` and if you're running on a different port than the default pass in `--port 8888`.
